name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 'intermediate/**'

jobs:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Test
          run: ./gradlew test